### ISSUE TITLE
onPacketReceiving NoClassDefFoundError TemporaryPlayer with ProtocolLib 4.3.0

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1732]
https://pastebin.com/HET9JuYs

**Server software:**
AAC 4.1.4
Paper 1.12.2
ProtocolLib 4.3.0
(ProtocolLib 4.4.0 works good without the crash!)

I can't update ProtocolLib to 4.4.0 on the server because of LibsDisguises, it doesn't work with ProtocolLib 4.4.0 on 1.12.2.

**Comment by konsolas** [comment]
Do you know why LibsDisguises doesn't work on 4.4.0?

**Comment by BestMark** [comment]
LibsDisguises works with ProtocolLib 4.4.0, but only on MC 1.13+. Author recommended using ProtocolLib 4.3.0 for 1.12.2 version. Could you add compatibility with ProtocolLib 4.3.0?
![Uploading image.png…]()

**Comment by BestMark** [comment]
I found LibsDisguises for latest AAC: https://github.com/libraryaddict/LibsDisguises/issues/357

**Comment by BestMark** [comment]
Sorry, but the version for 4.4.0 doesn't work at all.

**Comment by konsolas** [comment]
4.1.5, but please find a way to update to the correct version of ProtocolLib as soon as possible.
